[package]
name = "serial_plotter"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdk = "^0.15.0"
gtk = "^0.15.0"
relm = "^0.23.0"
relm-derive = "^0.23.0"
serial = "*"

